#!/bin/bash
print_help() {
    echo "Usage:[dir]"
    echo
    echo "Script found all catalogs, in which the files were not opened"
    echo "Parametrs:"
    echo "  -h, --help    help output"
}


if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    print_help
    exit 0
fi

dir=${1:-.}

if [[ ! -d "$dir" ]]; then
    echo "Error" >&2
    exit 1
fi

subdirs=$(find "$dir" -mindepth 1 -maxdepth 1 -type d)

found_empty=true
for subdir in $subdirs; do
    lsof +D "$subdir" >/dev/null 2>&1
    lsof_exit_code=$?

    if [[ $lsof_exit_code -eq 1 ]]; then
        echo "$(realpath "$subdir")"
        found_empty=false
    elif [[ $lsof_exit_code -ne 0 ]]; then
        echo "Error" >&2
        exit $lsof_exit_code
    fi
done

if $found_empty; then
    echo "nothing found"
    exit 1
fi
